version: 1.0.{build}

platform: 
 - x86
 - x64
configuration: 
 - Debug
 - Release

clone_folder: c:\alive

before_build:
 - mkdir build
 - cd build
 - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%
 - cmake --help
 - if %platform%==x64 (cmake .. -G "Visual Studio 12 2013 Win64")
 - if %platform%==x86 (cmake .. -G "Visual Studio 12 2013")

build_script:
 - cmake --build . --config %configuration% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 # Gotta use the full path to cpack because chocolatey replaces cpack with itself!
 - "C:\Program Files (x86)\CMake\bin\cpack" --help
 - "C:\Program Files (x86)\CMake\bin\cpack" -G WiX -C %configuration%
 - ctest -VV

install:
 - git submodule update --init --recursive
 - ps: Start-FileDownload 'https://www.libsdl.org/release/SDL2-devel-2.0.3-VC.zip'
 - 7z x SDL2-devel-2.0.3-VC.zip
 - dir
 - dir "C:\Program Files\AppVeyor\"
 - dir "C:\"
 - dir "C:\Program Files\"
 - dir "C:\Program Files (x86)\"
 - set SDL2DIR=C:\alive\SDL2-2.0.3
 - set COMMIT_SHA=%APPVEYOR_REPO_COMMIT:~0,8%

artifacts:
 - path: bin
   name: Alive-$(configuration)-$(COMMIT_SHA)
