version: 1.0.{build}

platform: 
 - x86
 - x64
configuration: 
 - Debug
 - Release

clone_folder: c:\alive

before_build:
 - mkdir build
 - cd build
 - if %platform%==x64 (cmake .. -G "Visual Studio 13 Win64")
 - if %platform%==x86 (cmake .. -G "Visual Studio 13")

build_script:
 - cmake --build . --config $(configuration) -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 - cpack -C $(configuration)
 - ctest -VV

install:
 - git submodule update --init --recursive
 - ps: Start-FileDownload 'https://www.libsdl.org/release/SDL2-devel-2.0.3-VC.zip'
 - 7z x SDL2-devel-2.0.3-VC.zip
 - dir
 - set SDL2DIR=C:\alive\SDL2-2.0.3
 - set COMMIT_SHA=%APPVEYOR_REPO_COMMIT:~0,8%

artifacts:
 - path: bin
   name: Alive-$(configuration)-$(COMMIT_SHA)
